name: Build
on:
  push:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    - run: |
        ./build.sh
    - uses: actions/upload-artifact@v3
      with:
        name: gnupg.zip
        path: gnupg.zip
